profiles:
  active: 'dev'

  common:
    version: 0.1
    sqlite_uri_use_basedir: True
    flask:
      SECRET_KEY: 'secret_key'
      DEBUG: False

  dev:
    flask:
      DEBUG: True
      SQLALCHEMY_DATABASE_URI: 'sqlite:///boilerplate_main.db'
      SQLALCHEMY_TRACK_MODIFICATIONS: False

  prod:
    flask:
      SQLALCHEMY_DATABASE_URI: 'sqlite:///boilerplate_main.db'

  test:
    flask:
      DEBUG: True
      SQLALCHEMY_DATABASE_URI: 'sqlite:///boilerplate_main.db'
      TESTING: True